[package]
name = "oxidio-cli"
description = "Terminal UI for Oxidio music player"
readme = "../../README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "oxidio"
path = "src/main.rs"

[dependencies]
oxidio-core.workspace = true
oxidio-protocol.workspace = true
oxidio-ctl.workspace = true
oxidio-web = { workspace = true, optional = true }
ratatui.workspace = true
crossterm.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
dirs.workspace = true
discord-rich-presence = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"

[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
souvlaki = "0.7"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9"
objc = "0.2"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_System_Console",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Storage_FileSystem",
] }

[features]
default = ["web"]
web = ["oxidio-web"]

[build-dependencies]
winres = "0.1"
