[package]
name = "horikawa-cli"
description = "Horikawa music player binary"
readme = "../../README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "horikawa"
path = "src/main.rs"

[dependencies]
horikawa-tui.workspace = true
anyhow.workspace = true

[build-dependencies]
winres = "0.1"
